config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :profiles

  resources :posts do
    resources :comments
    resources :reactions
  end

  get "about" => "abouts#show", as: :about


  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :user, class_name: "User"

  validates :follower_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :reactions
  has_one_attached :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :bio, length: { maximum: 500 }
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  # User can follow other users
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :user

  # Users can be followed by other users
  has_many :passive_follows, class_name: "Follow", foreign_key: "user_id", dependent: :destroy
  has_many :followers, through: :passive_follows

  after_create :create_profile

  private

  def create_profile
    Profile.create(user: self)
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@post), notice: "Comentario agregado correctamente."
    else
      redirect_to post_path(@post), alert: "Hubo un error al agregar el comentario."
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to root_path, notice: "Your Post created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path, notice: "Your Post updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: "Your Post deleted successfully."
  end

  private
  
  def post_params
    params.require(:post).permit(:content, :link, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile

    if @profile.update(profile_params)
      redirect_to root_path, notice: "Profile updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @profile = current_user.profile

    @my_posts = current_user.posts
  end

  private

  def profile_params
    params.require(:profile).permit(:bio, :profile_picture)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/layouts/_header.html.erb
<div class="flex items-center absolute">
  <h1 class="text-5xl font-bold"><%= link_to "Book Hub", root_path %></h1>

  <div class="flex items-center">
    <% if user_signed_in? %>
      <div class="flex items-center">
        <p class="mr-4">Hola, <%= current_user.email %></p>
        <%= link_to "Cerrar Sesión", destroy_user_session_path, data: { turbo_method: :delete }%>
      </div>

    <% else %>
      <div class="flex items-center">
        <%= link_to "Iniciar Sesión", new_user_session_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="bg-slate-800 max-h-full w-1/4 left-0 text-3xl font-bold">
  <nav class="py-12 px-4">
    <ul>
      <li class="mb-4"><%= link_to "New Post", new_post_path if user_signed_in? %></li>
      <li class="mb-4"><%= link_to "Home", root_path %></li>
      <li class="mb-4"><%= link_to "My Profile", profile_path(current_user) if user_signed_in? %></li>
      <li class="bottom-4 absolute"><%= link_to "About Us", about_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_posts.html.erb
<% posts.each do |post| %>
    <div class="flex flex-row bg-slate-800 max-h-96 w-auto p-2 m-2 justify-between">
      <div class="flex flex-col w-5/12 h-full">
        <p>De: <%= post.user.email %></p>

        <p class="text-2xl align-middle whitespace-normal mt-4 flex flex-col space-y-2 overflow-y-auto max-h-96  w-full p-2 rounded bg-slate-700"><%= post.content %></p>

        <p class="my-8 text-2xl">
          <%= link_to post.link, target: "_blank" do %>
            🕮  Link al libro
          <% end %>
        </p>

        <div class="flex flex-row justify-between">
          <div class="flex flex-row">
            <p class="mr-4">Veces Recomendado: <%= post.reactions.where(reaction_type: "star").count %></p>
            <% if user_signed_in? %>
              <% if post.reactions.exists?(user_id: current_user.id) and post.reactions.exists?(reaction_type: "star") %>
                <%= form_with model: post.reactions.find_by(user_id: current_user.id), url: post_reactions_path(post), local: true do |f| %>
                  <%= f.hidden_field :reaction_type, value: "unstar" %>
                  <%= f.submit "✯", class: "mr-4" %>
                <% end %>
              <% else %>
                <%= form_with model: Reaction.new, url: post_reactions_path(post), local: true do |f| %>
                  <%= f.hidden_field :reaction_type, value: "star" %>
                  <%= f.submit "☆", class: "mr-4" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="flex flex-row justify-between">
          <% if user_signed_in? %>
            <% if post.user_id == current_user.id %>
              <%= link_to "Editar Post", edit_post_path(post) %>
              <%= link_to "Borrar Post", post, method: :delete, data: { turbo_method: :delete } %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="flex items-center justify-center w-4/12">
        <p><%= image_tag post.image, width: 250, height: 350 if post.image.present? %></p>
      </div>

      <div class="flex flex-col items-center justify-center w-4/12">
        <p class="text-2xl">Comentarios</p>
        <%= render 'comments/comments', post: post %>

        <% if user_signed_in? %>
          <%= render 'comments/form', post: post %>
        <% end %>

      </div>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-900 text-white max-h-screen">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <header class="bg-slate-800 h-16 w-full flex justify-between items-center top-0 shadow-md absolute">
      <%= render 'layouts/header' %>
    </header>

    <div class="container mt-16 flex gap-4 w-full max-h-full">
      <%= render 'layouts/nav' %>
      <%= yield %>
    </div>
  </body>
</html>